=== Adri-123/TECNOLOGIAS-WEB/ejercicio1-2.dtd
<!ELEMENT usuarios (proveedor)>
<!ELEMENT proveedor (datos_personales,datos_fiscales,beneficios)>
<!ELEMENT datos_personales (id,nombre,edad,direccion)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT datos_fiscales (rfc,facturas_emitidas)>
<!ELEMENT rfc (#PCDATA)>
<!ELEMENT facturas_emitidas (#PCDATA)>
<!ELEMENT beneficios (descuento,mayoreo)>
<!ELEMENT descuento (#PCDATA)>
<!ELEMENT mayoreo (#PCDATA)>

=== Adri-123/TECNOLOGIAS-WEB/ejercicio1-2_dtd.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE usuarios SYSTEM "ejercicio1-2.dtd">
<usuarios>
    <proveedor>
        <datos_personales>
            <id>1</id>
            <nombre>Aaron</nombre>
            <edad>20</edad>
            <direccion>Masculino</direccion>
        </datos_personales>
        <datos_fiscales>
            <rfc>
                SDWQDQ31231DDSA
            </rfc>
            <facturas_emitidas>
                2
            </facturas_emitidas>
        </datos_fiscales>
        <beneficios>
            <descuento>0.15</descuento>
            <mayoreo>0.30</mayoreo>
        </beneficios>
    </proveedor>
</usuarios>
